version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Nothing in pre_build
  build:
    commands:
      - echo Build started
      - tsc
      - npm run build
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
