version:0.2

  phases:
    install:
      runtime-versions:
        nodejs: 16.16.0
      commands:
        - npm install -g typescript
        - npm install
    pre_build:
      commands:
        - echo Nothing in pre_build
    build:
      commands:
        - echo Build started
        - npm run build
    post_build:
      commands:
        - echo Build complete
  cache:
    pahts:
      - 'node_modules/**/*
  artifacts:
    files:
      - '**/*'
    discard-paths: no
    base-directory: build
